rearrange and rewrite some scripts in bin
Former-commit-id: bdf5cfe2635e7b18130e8e158061030dff23f2b4

diff --git a/bin/scrape_stats b/bin/scrape_stats
--- a/bin/scrape_stats
+++ b/bin/scrape_stats
@@ -1,13 +1,16 @@
 #!/usr/bin/env bash
-if [ -z $1 ] || [ $1 == "help" ]
-then
-  echo "usage: ./scrape_stats <usernames-csv-file> <output-csv-file>"
-  exit 1
+usage="usage: ./scrape_stats <usernames-csv-file> <output-csv-file>" && exit 1
+if [ $1 == "help" ]; then
+  echo "$usage" && exit
+elif [ "$#" -ne 2 ]; then
+  echo "$usage" && exit 1
+elif [ ! -f $1 ]; then
+  echo "input file '$1' not found" && exit 1
 fi
 
 ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/.."
 cd "$ROOT_DIR" && source env/bin/activate && \
-until python src/scrape/scrape_stats.py $1 $2
+until src/scrape/python -m scrape_stats $1 $2
 do
   bin/reset_vpn
 done
diff --git a/bin/upload_gdrive b/bin/upload_gdrive
--- a/bin/upload_gdrive
+++ b/bin/upload_gdrive
@@ -1,19 +1,17 @@
 #!/usr/bin/env bash
-if [ "$#" -ne 3 ]
-then
+if [ "$#" -ne 3 ]; then
   echo "usage: ./upload_gdrive <statsfile> <centroidsfile> <clusteridsfile>"
   exit 1
+elif [ ! -f $1 ]; then
+  echo "stats file '$1' not found" && exit 1
+elif [ ! -f $2 ]; then
+  echo "centroids file '$2' not found" && exit 1
+elif [ ! -f $3 ]; then
+  echo "cluster IDs file '$3' not found" && exit 1
 fi
 stats_file=$1
 centroids_file=$2
 clusterids_file=$3
-if [ ! -f $1 ]; then
-  echo "stats file '$1' not found" && exit
-elif [ ! -f $2 ]; then
-  echo "centroids file '$2' not found" && exit
-elif [ ! -f $3 ]; then
-  echo "cluster IDs file '$3' not found" && exit
-fi
 
 ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/.."
 tmp_dir="$ROOT_DIR/.tmpzip"
