add k=2000 to grid_search, move master.sh to bin/dev/grid_search, switch ROOT_DIR->ROOTDIR and simplify expression for getting it, add crosshairs upon click which can be cleared by clicking again after moving the plot (debounced at 0.3 seconds as well), fix order of stats in table
Former-commit-id: 7db66d6c56afd326b4ed364a97f73644e7b4a466

diff --git a/bin/dev/ec2_setup b/bin/dev/ec2_setup
--- a/bin/dev/ec2_setup
+++ b/bin/dev/ec2_setup
@@ -5,20 +5,21 @@ sudo yum upgrade -y
 sudo yum install git docker -y
 
 sudo usermod -aG docker ec2-user
-newgrp docker << EOF # newgrp spawns a new shell - start docker daemon and exit.
+newgrp docker <<EOF # newgrp spawns a new shell - start docker daemon and exit.
 sudo service docker start
 EOF
 docker run hello-world
 
 if ! [ -f ~/.ssh/id_ed25519 ]; then
-  ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -C osrs-hiscores-ec2-instance -q -N ""
+    ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -C osrs-hiscores-ec2-instance -q -N ""
 fi
 
-git -C ~/osrs-hiscores pull || \
-if ! git clone git@github.com:lukearend/osrs-hiscores.git; then
-  echo -e "\nClone failed, do you need to add your public key?\n" \
-          "Go to https://github.com/settings/keys and add:\n" ; \
-  cat ~/.ssh/id_ed25519.pub ; exit 1
-fi
+git -C ~/osrs-hiscores pull ||
+    if ! git clone git@github.com:lukearend/osrs-hiscores.git; then
+        echo -e "\nClone failed, do you need to add your public key?\n" \
+            "Go to https://github.com/settings/keys and add:\n"
+        cat ~/.ssh/id_ed25519.pub
+        exit 1
+    fi
 
 cd osrs-hiscores && git checkout development && make init
diff --git a/bin/dev/run_scrape b/bin/dev/run_scrape
--- a/bin/dev/run_scrape
+++ b/bin/dev/run_scrape
@@ -1,18 +1,20 @@
 #!/usr/bin/env bash
 
-ROOTDIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/../.."
+ROOTDIR="$(cd $(dirname "$0") && pwd)/../.."
 outfile="$ROOTDIR/data/raw/player-stats-raw.csv"
-cd "$ROOTDIR" && source env/bin/activate && \
+cd "$ROOTDIR" && source env/bin/activate
 
 function scrape {
-  python scripts/scrape_hiscores.py "$outfile" --start-rank 1 --stop-rank 2000000 \
-    --num-workers 28 --log-file /tmp/scrape.log --log-level INFO --usevpn
+    python scripts/scrape_hiscores.py "$outfile" --start-rank 1 --stop-rank 2000000 \
+        --num-workers 28 --log-file /tmp/scrape.log --log-level INFO --usevpn
 }
 
 while true; do
-  scrape ; retcode=$?; if [ $retcode == 0 ] || [ $retcode == 2 ]; then
-    exit 0
-  else
-    echo "script failed, restarting..."
-  fi
+    scrape
+    retcode=$?
+    if [ $retcode == 0 ] || [ $retcode == 2 ]; then
+        exit 0
+    else
+        echo "script failed, restarting..."
+    fi
 done
