increase EC2 compatibility
Former-commit-id: 8601847cec841b3acadee6fccc2d9427fa16ecea

diff --git a/bin/dev/ec2_setup b/bin/dev/ec2_setup
--- a/bin/dev/ec2_setup
+++ b/bin/dev/ec2_setup
@@ -1,23 +1,27 @@
 #!/usr/bin/env bash
-
-if ! [ -f ~/.ssh/id_ed25519 ]; then
-  ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -C osrs-hiscores-ec2-instance -q -N ""
-  echo "Generated SSH pair. Public key:"
-  cat ~/.ssh/id_ed25519.pub
-  exit 0
-fi
+# Run this script on an EC2 instance to set it up for the first time.
 
 sudo yum upgrade -y
 sudo yum install git docker -y
 
 sudo usermod -aG docker ec2-user
-newgrp docker
-
+newgrp docker << EOF # newgrp spawns a new shell - start docker daemon and ~ it.
 sudo service docker start
+EOF
 docker run hello-world
 
 sudo amazon-linux-extras install epel -y
 sudo yum install openvpn -y
 
-sudo git pull git@github.com:lukearend/osrs-hiscores.git
+if ! [ -f ~/.ssh/id_ed25519 ]; then
+  ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -C osrs-hiscores-ec2-instance -q -N ""
+fi
+
+git -C ~/osrs-hiscores pull || \
+if ! git clone git@github.com:lukearend/osrs-hiscores.git; then
+  echo -e "\nClone failed, do you need to add your public key?\n" \
+          "Go to https://github.com/settings/keys and add:\n" ; \
+  cat ~/.ssh/id_ed25519.pub ; exit 1
+fi
+
 cd osrs-hiscores && git checkout development && make init
